
#Author: Srikaran Elakurthy

Import the POS oversampled train set and test set for using in Naive Bayes model and logistic model

Implementing the Multinomial Naive bayes classification on the above dataset.
Performing Cross validation with kfolds =5 and extract average accuracy
Performing the naive bayes model on whole train data and test it and storing the results into files

Implementing the logistic multi class classification on the above dataset.
Performing Cross validation with kfolds =5 and extract average accuracy and predicted the test dataset and stored the reults.

*Detailed description is written for many parts of the code below. Please read through for the same.

#Command to run the file: 

>Open the ipynb notebook in Jupyter Lab and go to the menu bar on the top, click on 'Run' and from the dropdown select the 'Run All' option to run
all the cells in the notebook. 

#Inputs and Outputs

Inputs:
> posovrsamprockredtrain.csv - The new data set with POS tags obtained from POS pre-processing script. This is only the train set.

> posovrsamprockredtest.csv - The new data set with POS tags obtained from POS pre-processing script. This is only the test set.



Outputs:
> Naiveposrockred1.pkl-Naiveposrockred2.pkl-Naiveposrockred3.pkl-Naiveposrockred4.pkl-Naiveposrockred5.pkl <- Cross validation naive bayes models
> respos_naiverockred1.csv-respos_naiverockred2.csv-respos_naiverockred3.csv-respos_naiverockred4.csv-respos_naiverockred5.csv <- cross validation results of naives bayes consists of csv files with actual and predicted values.
> Naivepos_results_rockred.txt <- Cross vsalidation  classification reports.

>logipos_rockred1.pkl , logipos_rockred2.pkl , logipos_rockred3.pkl ,logipos_rockred4.pkl ,logipos_rockred5.pkl <- Cross validation Logistic models

> respos_logi_pos_rockred1.csv , respos_logi_pos_rockred2.csv , respos_logi_pos_rockred3.csv,respos_logi_pos_rockred4.csv, respos_logi_pos_rockred5.csv <-  cross validation results of logistic consists of csv files with actual and predicted values.

>logipos_results.txt<- Cross vsalidation  classification reports.

>Naiveposrockred_full.pkl <-  final model for naive bayes

>respos_naiverockred_full.csv<- test data predicted values and actual values are presented in a csv file.

>Naivepos_results_full.txt<- Cross validation report of final naive bayes model.

>logiposrockred_full.pkl<- final model for logistic model 

>respos_logirockred_full.csv <- test data logistic predicted values and actual values are presented in a csv file

>logipos_results_full.txt <- Classification report for a logistic model



INPUT: The inputs are posovrsamprockredtrain.csv and posovrsamprockredtest.csv
OUTPUT:

For Naive BAyes:
report:
              precision    recall  f1-score   support

       Other       0.85      0.02      0.03      5753
        Rock       0.98      0.06      0.12      5725
     Country       0.96      0.75      0.84      5694
     Electronic    0.80      0.66      0.72      5708
       Indie       1.00      0.13      0.24      5448
       Metal       0.66      0.05      0.09      4340
     Hip-Hop       0.97      0.16      0.27      5650
         Pop       0.72      0.20      0.31      5433
        Folk       0.52      0.03      0.06      7014
         R&B       0.94      0.20      0.33      5381
        Jazz       0.19      0.99      0.32     10111
    accuracy                           0.34     66257
    macro avg       0.78      0.30      0.30     66257
    weighted avg       0.74      0.34      0.30     66257

For Logistic model:
report:
              precision    recall  f1-score   support

       Other       0.87      0.09      0.16      5753
        Rock       0.51      0.91      0.65      5725
     Country       0.82      0.99      0.90      5694
     Electronic    0.93      0.61      0.73      5708
       Indie       0.97      0.67      0.79      5448
       Metal       0.47      0.75      0.57      4340
     Hip-Hop       0.66      0.78      0.71      5650
         Pop       0.32      0.96      0.49      5433
        Folk       0.57      0.16      0.25      7014
         R&B       0.66      0.96      0.78      5381
        Jazz       0.67      0.10      0.18     10111

    accuracy                           0.58     66257
    macro avg       0.68      0.63      0.57     66257
    weighted avg       0.68      0.58      0.53     66257



Importing the necessary python packages and reading pos over sampled train data and removing the unnamed column

In [ ]:
import numpy as np
import pandas as pd
import re
from nltk import pos_tag
import nltk
#nltk.download('averaged_perceptron_tagger')
#from langdetect import detect
import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.stem import PorterStemmer
#import emoji
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn.utils import shuffle
from sklearn.externals import joblib 
from sklearn.preprocessing import Normalizer
from scipy.sparse import hstack
from sklearn.metrics import classification_report
from statistics import mean
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
df=pd.read_csv("posovrsamprockredtrain.csv")
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
#df.drop('index', axis=1, inplace=True)
#df=shuffle(df)


In [ ]:
df.head()

lyrics       genre  ...  POS   LS
0  a kay a kay jordan de shoe pairan vich kaali h...       Other  ...  0.0  0.0
1  i remeb when i saw you at the diner s yet my h...        Rock  ...  0.0  0.0
2  you left the water run when you left me here b...     Country  ...  0.0  0.0
3  thing that happen when you fall asleep when yo...  Electronic  ...  0.0  0.0
4  oh my god my heart s as heavi as a stone and w...       Indie  ...  0.0  0.0

[5 rows x 40 columns]

Dividing the dataframe into lyrics and genre and pos data 

In [ ]:
rawdf=df.iloc[:,0:2]
posdf=df.iloc[:,2:41]
lyrics=rawdf['lyrics']
genre=rawdf['genre']

In [ ]:
lyrics.head()

0    a kay a kay jordan de shoe pairan vich kaali h...
1    i remeb when i saw you at the diner s yet my h...
2    you left the water run when you left me here b...
3    thing that happen when you fall asleep when yo...
4    oh my god my heart s as heavi as a stone and w...
Name: lyrics, dtype: object

In [ ]:
genre.head()

0         Other
1          Rock
2       Country
3    Electronic
4         Indie
Name: genre, dtype: object

Performing cross validation with 5 splits and implementing tfidf vectorization inside the cross validation to avoid any data leakage.
TFidf Vectorization will consider parameters stop_words= english specifying that it will be removing any english words and says to consider both unigrams and bigrams.

  We will extract the pos data using the train and test indexes and perform normalisation on pos data and horizontally stack withtfidf matrix and as given as a input to model.

We are taking Multinomial Naive bayes model specifying we are seeking a multi class problem and alpha =1 specifying smoothing is allowed. 
Storing the models in pickle files using joblib and results with actual and predicted values into a csv file.
Storing the accuracy of every cross validation split into a list.

In [ ]:
skf = StratifiedKFold(n_splits=5, random_state=0)
i=0
naiverep=[]
naivescore=[]
for train_index, test_index in skf.split(lyrics, genre):
    print(train_index)
    print(test_index)
    x_train1, x_test1 = lyrics[train_index], lyrics[test_index]
    y_train, y_test = genre[train_index], genre[test_index]
    i=i+1
    tfidf = TfidfVectorizer(stop_words="english",ngram_range=(1,2))
    x_train1 = tfidf.fit_transform(x_train1)
    x_test1 = tfidf.transform(x_test1)
    print("tfidf"+str(i))
    posx_train=posdf.iloc[train_index]
    posx_test=posdf.iloc[test_index]
    scaler = Normalizer().fit(posx_train)
    normalizedX_tr = scaler.transform(posx_train)
    normalizedX_ts = scaler.transform(posx_test)
    x_train=hstack( [x_train1,normalizedX_tr] )
    x_test=hstack( [x_test1,normalizedX_ts] )
    print("Normalizer"+str(i))
    clf = MultinomialNB(alpha=1.0)
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    joblib.dump(clf, 'Naiveposrockred'+str(i)+'.pkl')
    score = accuracy_score(y_test, y_pred)
    rep=classification_report(y_test, y_pred, target_names=df.genre.unique())
    naiverep.append(naiverep)
    dat={'Actual':y_test,'pred':y_pred}
    resdf=pd.DataFrame(dat)
    resdf.to_csv('respos_naiverockred'+str(i)+'.csv')
    naivescore.append(score)
    print(score)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


[ 51850  51866  51875 ... 265023 265024 265025]
[    0     1     2 ... 54345 54349 54374]
tfidf1
Normalizer1
0.31121005169226124
[     0      1      2 ... 265023 265024 265025]
[ 51850  51866  51875 ... 107644 107658 107681]
tfidf2
Normalizer2
0.30770682011131023
[     0      1      2 ... 265023 265024 265025]
[104764 104787 104788 ... 160528 160554 160556]
tfidf3
Normalizer3
0.31055560796151305
[     0      1      2 ... 265023 265024 265025]
[158303 158310 158313 ... 213057 213074 213081]
tfidf4
Normalizer4
0.30865012734647673
[     0      1      2 ... 213057 213074 213081]
[211342 211344 211365 ... 265023 265024 265025]
tfidf5
Normalizer5
0.3131591359305726


Creating a file to write our classification report for our 5 results of Cross validation models and computing the average accuracy and writing them into the file.
The classification report is computed by using the results csv files containing the actual and predicted values of ech split.

In [ ]:
f=open("Naivepos_results_rockred.txt","a")
for i in range(1,6):
    f.write("\n report"+str(i)+":\n")
    dfr=pd.read_csv("respos_naiverockred"+str(i)+".csv")
    dfr.drop(dfr.columns[dfr.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
    f.write(classification_report(dfr.Actual, dfr.pred, target_names=df.genre.unique()))
f.write("\nThe average score for this model is")
f.write(str(mean(naivescore)))
f.close()

Performing cross validation with 5 splits and implementing tfidf vectorization inside the cross validation to avoid any data leakage.



*   TFidf Vectorization will consider parameters stop_words= english specifying that it will be removing any english words and says to consider both unigrams and bigrams.
*   We will extract the pos data using the train and test indexes and perform normalisation on pos data and horizontally stack withtfidf matrix and as given as a input to model.

*   We are specifying the parameters on logistic model as multiclass as multinonial specifying we are seeking a multi class problem and optimization algorithm as 'sag'. Using sag so that the it is best for converging fastly on large datasets.


*   Storing the models in pickle files using joblib  and results with actual and predicted values into a csv file.
*   Storing the accuracy of every cross validation split into a list.





In [ ]:
skf = StratifiedKFold(n_splits=5, random_state=0)
i=0
logirep=[]
logiscore=[]
for train_index, test_index in skf.split(lyrics, genre):
    print(train_index)
    print(test_index)
    x_train1, x_test1 = lyrics[train_index], lyrics[test_index]
    y_train, y_test = genre[train_index], genre[test_index]
    i=i+1
    tfidf = TfidfVectorizer(stop_words="english",ngram_range=(1,2))
    x_train1 = tfidf.fit_transform(x_train1)
    x_test1 = tfidf.transform(x_test1)
    print("tfidf"+str(i))
    posx_train=posdf.iloc[train_index]
    posx_test=posdf.iloc[test_index]
    scaler = Normalizer().fit(posx_train)
    normalizedX_tr = scaler.transform(posx_train)
    normalizedX_ts = scaler.transform(posx_test)
    x_train=hstack( [x_train1,normalizedX_tr] )
    x_test=hstack( [x_test1,normalizedX_ts] )
    print("Normalizer"+str(i))
    clf = LogisticRegression(multi_class='multinomial',solver='sag')
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    joblib.dump(clf, 'logipos_rockred'+str(i)+'.pkl')
    score = accuracy_score(y_test, y_pred)
    rep=classification_report(y_test, y_pred, target_names=df.genre.unique())
    logirep.append(naiverep)
    dat={'Actual':y_test,'pred':y_pred}
    resdf=pd.DataFrame(dat)
    resdf.to_csv('respos_logi_pos_rockred'+str(i)+'.csv')
    logiscore.append(score)
    print(score)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


[ 51850  51866  51875 ... 265023 265024 265025]
[    0     1     2 ... 54345 54349 54374]
tfidf1
Normalizer1
0.7411613779572124
[     0      1      2 ... 265023 265024 265025]
[ 51850  51866  51875 ... 107644 107658 107681]
tfidf2
Normalizer2
0.7391755494764645
[     0      1      2 ... 265023 265024 265025]
[104764 104787 104788 ... 160528 160554 160556]
tfidf3
Normalizer3
0.7411942269597208
[     0      1      2 ... 265023 265024 265025]
[158303 158310 158313 ... 213057 213074 213081]
tfidf4
Normalizer4
0.7417602113008207
[     0      1      2 ... 213057 213074 213081]
[211342 211344 211365 ... 265023 265024 265025]
tfidf5
Normalizer5
0.741665880577304


Perform tfidf vectorization to extraxt tfidf matrix on whole training data and use the fitted vectorizer to transform the test data to tfidf matrix.

Tfidf matrix considers:
*   Removing stop words
*   Considering both unigrams and bigrams



In [ ]:
f=open("logipos_results.txt","a")

for i in range(1,6):
    f.write("\n report"+str(i)+":\n")
    dfr=pd.read_csv("respos_logi_pos_rockred"+str(i)+".csv")
    dfr.drop(dfr.columns[dfr.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
    f.write(classification_report(dfr.Actual, dfr.pred, target_names=df.genre.unique()))
f.write("\nThe average score for this model is")
f.write(str(mean(logiscore)))
f.close()

Importing the test dataset

In [ ]:
tdf=pd.read_csv("posovrsamprockredtest.csv")

Removing the unnamed column

In [ ]:
tdf.drop(tdf.columns[tdf.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

In [ ]:
tdf.head()

lyrics    genre  ...    $  NNPS
0  when a cold chill begin to burn at your veri s...      R&B  ...  0.0   0.0
1  when the boy wa no more than a shaver hi old m...  Country  ...  0.0   0.0
2  mayb i can t live to love you as long as i wan...     Jazz  ...  0.0   0.0
3  artist erick sermon f al green album react son...  Hip-Hop  ...  0.0   0.0
4  in a simpl life dream die hard you never let e...  Country  ...  0.0   0.0

[5 rows x 40 columns]

Dividing the dataframe into lyrics and genre and pos data 

In [ ]:
trawdf=tdf.iloc[:,0:2]
tposdf=tdf.iloc[:,2:41]
tlyrics=trawdf['lyrics']
tgenre=trawdf['genre']

TFidf Vectorization will consider parameters stop_words= english specifying that it will be removing any english words and says to consider both unigrams and bigrams.
*   We will use the pos data to perform normalisation on pos data and horizontally stack with tfidf matrix and as given as a input to model.


In [ ]:
tfidf = TfidfVectorizer(stop_words="english",ngram_range=(1,2))
x_train1 = tfidf.fit_transform(lyrics)
x_test1 = tfidf.transform(tlyrics)
print("tfidf")
posx_train=posdf.copy()
posx_test=tposdf.copy()
scaler = Normalizer().fit(posx_train)
normalizedX_tr = scaler.transform(posx_train)
normalizedX_ts = scaler.transform(posx_test)
x_train=hstack( [x_train1,normalizedX_tr] )
x_test=hstack( [x_test1,normalizedX_ts] )
print("Normalizer")


tfidf
Normalizer


Performing Multi nomial Naive Bayes model with smoothing allowed and storing the model into a pickle file and results with actual and predicted into a csv file.

In [ ]:
clf = MultinomialNB(alpha=1.0)
clf.fit(x_train, genre)
y_pred = clf.predict(x_test)
joblib.dump(clf, 'Naiveposrockred_full.pkl')
score = accuracy_score(tgenre, y_pred)
nairep=classification_report(tgenre, y_pred, target_names=df.genre.unique())
dat={'Actual':tgenre,'pred':y_pred}
resdf=pd.DataFrame(dat)
resdf.to_csv('respos_naiverockred_full.csv')

Computing the classification report and store into a file

In [ ]:
f=open("Naivepos_results_full.txt","a")

f.write("\n report:\n")
dfr=pd.read_csv("respos_naiverockred_full.csv")
dfr.drop(dfr.columns[dfr.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
f.write(classification_report(dfr.Actual, dfr.pred, target_names=df.genre.unique()))
f.close()


Declaring the logistic model with multinomial as parameter specifying that we are trying to solve a multi classification problem and sag optimiazation is used as it is best for large datasets and have faster convergence.


Fitting the model and storing into a pickle file

predicting the results and storing into a csv file consisting the actual vs predicted for test data.



In [ ]:
logi =  LogisticRegression(multi_class='multinomial',solver='sag')
logi.fit(x_train, genre)
y_pred = logi.predict(x_test)
joblib.dump(logi, 'logiposrockred_full.pkl')
score = accuracy_score(tgenre, y_pred)
logrep=classification_report(tgenre, y_pred, target_names=df.genre.unique())
dat={'Actual':tgenre,'pred':y_pred}
resdf=pd.DataFrame(dat)
resdf.to_csv('respos_logirockred_full.csv')

Computing the classification report and store into a file

In [ ]:
f=open("logipos_results_full.txt","a")
f.write("\n report:\n")
dfr=pd.read_csv("respos_logirockred_full.csv")
dfr.drop(dfr.columns[dfr.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
f.write(classification_report(dfr.Actual, dfr.pred, target_names=df.genre.unique()))
f.close()